[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run serve"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks.environment]
NODE_VERSION = "20"